- docs/templates/strix/styles/main.css
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/arlodotexe/strix-music/issues).
> Apply fixes from CodeFactor

- src/Sdk/StrixMusic.Sdk/Plugins/PlaybackHandler/StrixDataRootPlaybackHandlerPlugin.cs
> [breaking] StrixDataRootPlaybackHandlerPlugin is now internal

- src/Sdk/StrixMusic.Sdk.Tests/FileMetadata/Repositories/TrackRepositoryTests.cs
- src/Sdk/StrixMusic.Sdk.Tests/Mock/FileSystem/InMemoryFileData.cs
- src/Sdk/StrixMusic.Sdk.Tests/Mock/FileSystem/InMemoryFolderData.cs
- src/Sdk/StrixMusic.Sdk.Tests/StrixMusic.Sdk.Tests.csproj
- src/Sdk/StrixMusic.Sdk/FileMetadata/Repositories/TrackRepository.cs
> [improvement] Album tracks from file-based cores are now grouped by disc number

- src/Cores/Files/StrixMusic.Cores.Files/FilesCore.cs
- src/Cores/Files/StrixMusic.Cores.LocalFiles/LocalFilesCore.cs
- src/Cores/Files/StrixMusic.Cores.OneDrive/OneDriveCore.cs
- src/Sdk/StrixMusic.Sdk/FileMetadata/FileMetadataManager.cs
- src/Sdk/StrixMusic.Sdk/FileMetadata/FileScanState.cs
- src/Sdk/StrixMusic.Sdk/FileMetadata/FileScanningType.cs
- src/Shared/AppLoadingView.xaml.cs
Closes #157 
FileMetadataManager and all file-based cores now report scan progress via the Progress{T} in the constructor.
Not provided
> [breaking] Removed INotificationService dependency in FileMetadataManager

- src/Sdk/StrixMusic.Sdk/FileMetadata/Scanners/AudioMetadataScanner.cs
Fixed potential crash when artist is missing genre information
Not provided
> [fix] Fixed potential crash when artist is missing genre information

- src/Shared/SuperShell.xaml.cs
> [fix] Fixed disconnect button not showing in services view

- build-scripts/GenerateChangelogs.ps1
- docs/reference/changelogs/app/alpha/0.0.10-app-alpha.md
- docs/reference/changelogs/app/alpha/0.0.11-app-alpha.md
- docs/reference/changelogs/app/alpha/0.0.3-app-alpha.md
- docs/reference/changelogs/app/alpha/0.0.4-app-alpha.md
- docs/reference/changelogs/app/alpha/0.0.5-app-alpha.md
- docs/reference/changelogs/app/alpha/0.0.6-app-alpha.md
- docs/reference/changelogs/app/alpha/0.0.7-app-alpha.md
- docs/reference/changelogs/app/alpha/0.0.8-app-alpha.md
- docs/reference/changelogs/app/alpha/0.0.9-app-alpha.md
- docs/reference/changelogs/sdk/alpha/0.0.1-sdk-alpha.md
- docs/reference/changelogs/sdk/alpha/0.0.2-sdk-alpha.md
- docs/reference/changelogs/sdk/alpha/0.0.3-sdk-alpha.md
- docs/reference/changelogs/sdk/alpha/0.0.4-sdk-alpha.md
- docs/reference/changelogs/sdk/alpha/0.0.5-sdk-alpha.md
- docs/reference/changelogs/sdk/alpha/0.0.6-sdk-alpha.md
- docs/reference/changelogs/sdk/alpha/0.0.7-sdk-alpha.md
- docs/reference/changelogs/sdk/alpha/0.0.8-sdk-alpha.md
- docs/reference/changelogs/sdk/alpha/0.0.9-sdk-alpha.md
> Fixed all tags showing under title in generated changelogs

- src/Sdk/StrixMusic.Sdk.WinUI/Styles/Shells/NowPlayingBarStyle.xaml
Closes #194
Fixed dataType and binding in NowPlayingBarDataTemplate for sandbox shell.
https://user-images.githubusercontent.com/15306909/178046434-ea8cc38a-1c77-44e2-8e34-cf700bac48f5.mp4
Not provided
> [fix] Fixed InvalidCastException when loading sandbox shell.

- src/Sdk/StrixMusic.Sdk.WinUI/Services/Navigation/NavigationService.cs
- src/Sdk/StrixMusic.Sdk.WinUI/Styles/Shells/NowPlayingBarStyle.xaml
Closes #189 
Prevented the navigation service from adding duplicate registeredPages.
https://user-images.githubusercontent.com/15306909/178027971-2bb54250-8c77-4900-b1c1-8176ae494bc3.mp4
Not provided
> [fix] Fixed an issue where the app is crashing on shell switch.

- src/Platforms/StrixMusic.Wasm/StrixMusic.Wasm.csproj
- src/Platforms/StrixMusic.Wasm/wwwroot/SharedArrayBufferServiceWorker.js
- src/Platforms/StrixMusic.Wasm/wwwroot/index.html
- src/Platforms/StrixMusic.Wasm/wwwroot/scripts/EnableSharedArrayBuffer.js
> [fix] Fixed WASM app not loading due to missing SharedArrayBuffer

- src/Platforms/StrixMusic.UWP/StrixMusic.UWP.csproj
Closes #205 
Screenshot of the fix:
Not provided
> [fix] Fixed UWP project not being deployable in Visual Studio

- src/Shared/Controls/StrixIcon.xaml
> [improvement] Lightly slowed loading icon animation

- src/Sdk/StrixMusic.Sdk.WinUI/Controls/SafeImage.cs
A minor improvement that cancels ongoing loading tasks when the source of a SafeImage is changed. Helps with resource usage when loading many, many images on a slow machine.
Not provided
> [improvement] Added loading cancellation to SafeImage when image is changed

- src/Shells/StrixMusic.Shells.ZuneDesktop/Controls/Views/Collection/ZuneTrackCollection.cs
- src/Shells/StrixMusic.Shells.ZuneDesktop/Controls/Views/Collection/ZuneTrackCollectionItem.cs
- src/Shells/StrixMusic.Shells.ZuneDesktop/Styles/Collections/TrackCollectionStyle.xaml
Progress toward #129
The track collection was missing sorting functionality unlike aritsts or albums.
The functionality has been implementation. 
https://user-images.githubusercontent.com/15306909/190857558-dfa44021-f114-4ef8-af72-7f49e94557f1.mp4
Not provided
> [new] Alphanumeric sorting on track collection.

- www/index.html
> [improvement] Updated website homepage

- src/Shells/StrixMusic.Shells.Groove/Styles/Pages/GrooveArtistPageStyle.xaml
Closes #248 
The issue was with the missing binding in the GrooveArtistPage which has now fixed.
Not provided
> [fix] Groove track collection playback.

- src/Cores/Storage/src/ComponentModel/IMusicProperties.cs
- src/Cores/Storage/src/FileMetadata/FileMetadataManager.cs
- src/Cores/Storage/src/FileMetadata/Scanners/DepthFirstFolderScanner.cs
- src/Cores/Storage/src/FileMetadata/Scanners/IFolderScanner.cs
- src/Cores/Storage/src/FileMetadata/Scanners/PlaylistMetadataScanner.Helpers.cs
- src/Cores/Storage/src/StorageCore.cs
- src/Cores/Storage/src/StrixMusic.Cores.Storage.csproj
- src/Libs/OwlCore.WinUI/OwlCore.WinUI.csproj
- src/Platforms/StrixMusic.UWP/StrixMusic.UWP.csproj
- src/Sdk/StrixMusic.Sdk.Tests/StrixMusic.Sdk.Tests.csproj
- src/Sdk/StrixMusic.Sdk.WinUI/StrixMusic.Sdk.WinUI.csproj
- src/Sdk/StrixMusic.Sdk/StrixMusic.Sdk.csproj
- src/Shared/AppModels/CoreFactory.cs
- src/Shared/AppModels/IpfsAccess.cs
- src/Shared/Controls/Settings/MusicSources/ConnectNew/OneDriveCore/FolderSelector.xaml
- src/Shared/Controls/Settings/MusicSources/ConnectNew/OneDriveCore/FolderSelector.xaml.cs
- src/Shared/Controls/Storage/FolderBrowser.xaml
- src/Shared/Controls/Storage/FolderBrowser.xaml.cs
- src/Shared/Settings/OneDriveCoreSettings.cs
- src/Shells/StrixMusic.Shells.Groove/StrixMusic.Shells.Groove.csproj
- src/Shells/StrixMusic.Shells.ZuneDesktop/StrixMusic.Shells.ZuneDesktop.csproj
Fixed breaking changes after updating the OwlCore and community toolkit packages.
Closes #0
Not provided
> [improvement] Update package dependencies to latest stable

- src/Shared/App.xaml.cs
- src/Shared/AppFrame.xaml.cs
- src/Shared/AppModels/AppDiagnostics.cs
- src/Shared/AppModels/AppRoot.cs
- src/Shared/AppModels/IntentionalCrashException.cs
- src/Shared/ApplicationHealthManager.cs
- src/Shared/ApplicationHealthState.cs
- src/Shared/Controls/AppRecovery.xaml
- src/Shared/Controls/AppRecovery.xaml.cs
- src/Shared/Controls/Diagnostics.xaml
- src/Shared/Controls/Diagnostics.xaml.cs
- src/Shared/MediaPlayback/SystemMediaTransportControlsHandler.cs
- src/Shared/Settings/AppSettingsSerializerContext.cs
- src/Shared/Settings/DiagnosticSettings.cs
- src/Shared/StrixMusic.Shared.projitems
This PR adds a basic app health monitor and crash recovery screen.
https://user-images.githubusercontent.com/9384894/227045007-1714b210-3dcd-4fab-b621-6bb42d9edbf0.mp4
Not provided
> [new] Added a basic app health monitor and crash recovery screen

- src/Platforms/StrixMusic.UWP/StrixMusic.UWP.csproj
- src/Platforms/StrixMusic.Wasm/StrixMusic.Wasm.csproj
- src/Shared/AppModels/IpfsAccess.cs
> [fix] Fixed KuboBootstrapper not starting, duplicated kubo binaries

- src/Cores/Storage/src/StrixMusic.Cores.Storage.csproj
- src/Libs/OwlCore.WinUI/OwlCore.WinUI.csproj
- src/Platforms/StrixMusic.Wasm/StrixMusic.Wasm.csproj
- src/Sdk/StrixMusic.Sdk.Tests/StrixMusic.Sdk.Tests.csproj
- src/Sdk/StrixMusic.Sdk.WinUI/Controls/Collections/Abstract/CollectionControl.cs
- src/Sdk/StrixMusic.Sdk.WinUI/StrixMusic.Sdk.WinUI.csproj
- src/Sdk/StrixMusic.Sdk/StrixMusic.Sdk.csproj
- src/Shells/StrixMusic.Shells.Groove/StrixMusic.Shells.Groove.csproj
- src/Shells/StrixMusic.Shells.ZuneDesktop/StrixMusic.Shells.ZuneDesktop.csproj
Closes #0
This PR updates all dependencies to the latest non-breaking versions.
Not provided
> [improvement] Updated all dependencies to latest non-breaking version

- src/Shared/AppModels/AppDiagnostics.cs
- src/Shared/Controls/Settings/MusicSources/MusicSourcesSettingsEditor.xaml.cs
> [fix] Fixed an issue where cores couldn't be removed
