Arlodotexe/strix-music

src/Sdk/StrixMusic.Sdk/FileMetadata/Scanners/PlaylistMetadataScanner.Parsers.cs
Closes #137
This PR adds and extra control flow in the M3U parser that ignores empty lines (which previously would have caused parsing to fail entirely, see linked issue). Note that it checks for null or whitespace, rather than simply checking line length. This is because empty lines will skip the `line[0] == '#'` branch and attempt to create a `Uri`, which will always fail if the line is empty. Since we have to check for line length anyway, we might as well skip all whitespace lines.
Not provided
=> [fix] Skip empty or whitespace lines in M3U playlists

src/Cores/Files/StrixMusic.Cores.LocalFiles/LocalFilesCore.cs, src/Cores/Files/StrixMusic.Cores.OneDrive/OneDriveCore.cs, src/Cores/Remote/StrixMusic.Cores.OwlCoreRpc.Tests/Mock/MockCore.cs, src/Sdk/StrixMusic.Sdk.Tests/Mock/Core/MockCore.cs
Closes #140
This PR fixes a regression in cores' use of `CoreMetadata.SdkVer`. Previously, they were hard-coded to `0.0.0.0`, which would cause an `IncompatibleSdkVersionException` to be thrown by the app, halting library initialization.
Not provided
=> [fix] Fixed crash caused by cores not always using current SDK version

src/Sdk/StrixMusic.Sdk/FileMetadata/Scanners/AudioMetadataScanner.cs
Progress towards #145 
AudioMetadataScanner now ignores files that throw `UnauthorizedAccessException` when scanning id3 data
Not provided
=> [fix] AudioMetadataScanner now ignores files that throw UnauthorizedAccessException when scanning id3 data

src/Cores/Files/StrixMusic.Cores.OneDrive/OneDriveCore.cs, src/Sdk/StrixMusic.Sdk.Tests/Services/MetadataScanner/AudioMetadataScanner.Tests.cs, src/Sdk/StrixMusic.Sdk/FileMetadata/FileMetadataManager.cs, src/Sdk/StrixMusic.Sdk/FileMetadata/IFileMetadataManager.cs, src/Sdk/StrixMusic.Sdk/FileMetadata/Scanners/AudioMetadataScanner.cs, src/Sdk/StrixMusic.Sdk/FileMetadata/Scanners/PlaylistMetadataScanner.Parsers.cs, src/Sdk/StrixMusic.Sdk/FileMetadata/Scanners/PlaylistMetadataScanner.cs
Closes #112
- The constructors for `FileMetadataManager`, `AudioMetadataScanner` and `PlaylistMetadataScanner` have been changed.
- `AudioMetadataScanner` no longer inherits the scan mode from `FileMetadataManager`. Instead, `FileMetadataManager` gets and sets the scan mode from `AudioMetadataScanner`.
- The property `IFileMetadataManager.DegreesOfParallelism` no longer has a public setter, properly reflecting that parallelism can't be changed after construction.
Not provided
=> [breaking] Removed unnecessary dependencies from metadata scanner constructors

src/Sdk/StrixMusic.Sdk.Tests/MetadataScanner/AudioMetadataScanner.Tests.cs, src/Sdk/StrixMusic.Sdk/FileMetadata/FileMetadataManager.cs, src/Sdk/StrixMusic.Sdk/FileMetadata/Scanners/AudioMetadataScanner.ImageProcessing.cs, src/Sdk/StrixMusic.Sdk/FileMetadata/Scanners/AudioMetadataScanner.cs
=> [breaking] Fixed AudioMetadataScanner.CacheFolder to be optional, and renamed it to ImageOutputFolder

src/Shells/StrixMusic.Shells.ZuneDesktop/Styles/NowPlaying/DefaultZuneMediaInfoStyle.xaml
Closes #104
This fixes an issue where a DataTemplate in DefaultDefaultMediaInfoStyle.xaml isn't able to typecast the NowPlayingBar to the DeviceViewModel.
Not provided
=> [fix] Fixed InvalidCastException when loading Zune shell with debugger attached

src/Sdk/StrixMusic.Sdk.WinUI/Controls/NowPlaying/MediaInfo.cs, src/Shells/StrixMusic.Shells.ZuneDesktop/Styles/NowPlaying/DefaultZuneMediaInfoStyle.xaml
Closes #188
Fixed an issue where seeking on zune shell wasn't working correctly.
The issue was with the MediaInfo binding and incorrect DataContext being passed to MediaInfo.
https://user-images.githubusercontent.com/15306909/177621232-208f1856-9ccb-4c00-b70d-77366d0a197d.mp4
Not provided
=> [fix] Fixed an issue where seeking on zune shell wasn't working correctly

src/Sdk/StrixMusic.Sdk.WinUI/Controls/NowPlaying/MediaInfo.cs, src/Sdk/StrixMusic.Sdk.WinUI/Controls/NowPlaying/MediaTransports.cs, src/Sdk/StrixMusic.Sdk.WinUI/Styles/Shells/NowPlayingBarStyle.xaml
Closes #196 
This fixes media transport buttons such as play/pause/forward/backward and shuffle.
This fixes media info such as album image in sandbox shell.
https://user-images.githubusercontent.com/15306909/180057868-f5e860e6-1fe9-4674-b942-ae78eba3df1a.mp4
Not provided
=> [fix] Fixed MediaInfo and MediaTransport in sandbox shell.

src/Sdk/StrixMusic.Sdk/ViewModels/AlbumCollectionViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/AlbumViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/ArtistCollectionViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/ArtistViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/Helpers/CollectionInit.cs, src/Sdk/StrixMusic.Sdk/ViewModels/PlayableCollectionGroupViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/PlaylistCollectionViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/PlaylistViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/TrackCollectionViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/TrackViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/UserProfileViewModel.cs
Closes #209 
Renamed all method names in the CollectionInit static class by appending "Async" suffix with them since all methods are awaitable tasks.
Not provided
=> [refactor] Added Async suffix to CollectionInit helper methods

src/Sdk/StrixMusic.Sdk/FileMetadata/Scanners/AudioMetadataScanner.cs
Fixed an issue where the metadata scanner could crash if abstract storage failed to provide optional artist data
Not provided
=> [fix] Fixed file metadata scanner crashing when FileProperties doesn't provide optional data

src/Cores/Files/StrixMusic.Cores.Files/FilesCore.cs, src/Cores/Files/StrixMusic.Cores.LocalFiles/LocalFilesCore.cs, src/Cores/Files/StrixMusic.Cores.LocalFiles/Logo.svg, src/Cores/Files/StrixMusic.Cores.LocalFiles/LogoImage.cs, src/Cores/Files/StrixMusic.Cores.LocalFiles/StrixMusic.Cores.LocalFiles.csproj, src/Cores/Files/StrixMusic.Cores.OneDrive/Logo.svg, src/Cores/Files/StrixMusic.Cores.OneDrive/LogoImage.cs, src/Cores/Files/StrixMusic.Cores.OneDrive/OneDriveCore.cs, src/Cores/Files/StrixMusic.Cores.OneDrive/StrixMusic.Cores.OneDrive.csproj, src/Sdk/StrixMusic.Sdk.Tests/Mock/Core/MockCore.cs, src/Sdk/StrixMusic.Sdk/AdapterModels/MergedCore.cs, src/Sdk/StrixMusic.Sdk/CoreModels/ICore.cs, src/Sdk/StrixMusic.Sdk/ViewModels/CoreViewModel.cs, src/Shared/AppLoadingView.xaml, src/Shared/AppLoadingView.xaml.cs, src/Shared/Controls/CoreImage.xaml, src/Shared/Controls/CoreImage.xaml.cs, src/Shared/Services/CoreMetadata.cs, src/Shared/StrixMusic.Shared.projitems, src/Shared/Styles/CoreItemStyle.xaml
Closes #221 
This PR 
- Adds a nullable `Logo` property of type `ICoreImage` to `ICore`, replacing the `LogoUri` that was on registration.
- Moved Id and DisplayName onto `ICore`.
- Removed the `SdkVer` property. We have no solid plans for this property, so we're removing it. It may be added back in the future.
- Fully removed `StrixMusic.Sdk.CoreModels.CoreMetadata` from the SDK. A copy has been moved to App-level code to maintain functionality while preparing for further refactors.
Not provided
=> [breaking] Removed CoreMetadata, refactored into ICore

src/Sdk/StrixMusic.Sdk/FileMetadata/FileMetadataManager.cs, src/Sdk/StrixMusic.Sdk/FileMetadata/Scanners/PlaylistMetadataScanner.cs
=> [breaking] Switched to IAsyncEnumerable, renamed to PlaylistMetadataScanner.ScanPlaylistsAsync  

src/Shells/StrixMusic.Shells.ZuneDesktop/Styles/Collections/TrackTableStyle.xaml
Closes N/A (No issue was filed for this)
There was a crash on zune shell where it was consistently crashing without the debugger attached.
https://user-images.githubusercontent.com/15306909/184946863-7ffb6a9e-e358-4ebd-aeaf-5a5569cee060.mp4
Not provided
=> [fix] Fixed Zune Desktop shell crashing when debugger isn't attached

src/Sdk/StrixMusic.Sdk.WinUI/DefaultShell.xaml.cs
Closes #193
Added NavigationService events cleanup which was causing a race condition b/w the instances of the DefaultShell to set the overlay content.
The cleanup is done on the DefaulfShell Unload.
Not provided
=> [fix] Fixed an issue where sandbox shell is not showing any song list when loaded second time.

src/Shared/StrixMusic.Shared.projitems
Closes #246
Removed the invalid `Compile` element from the shared project.
- [*] Tested and contains **NO** breaking changes or known regressions.
- [*] Tested with the upstream branch merged in.
- [*] Tests have been added for bug fixes / features (or this option is not applicable)
- [*] All new code has been documented (or this option is not applicable)
- [*] Headers have been added to all new source files (or this option is not applicable)
Not provided
=> [fix] Fixed app compile error 'SettingsTemplateSelector.cs could not be found'

src/Sdk/StrixMusic.Sdk/ViewModels/AlbumCollectionViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/AlbumViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/ArtistCollectionViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/ArtistViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/CoreViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/DeviceViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/DiscoverablesViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/LibraryViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/PlayableCollectionGroupViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/PlaylistCollectionViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/PlaylistViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/RecentlyPlayedViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/SearchHistoryViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/SearchResultsViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/SearchViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/StrixDataRootViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/TrackCollectionViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/TrackViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/UserProfileViewModel.cs, src/Sdk/StrixMusic.Sdk/ViewModels/UserViewModel.cs, src/StrixMusic.sln
Closes #241 
Every relevant class in the ViewModel layer now exposes the model they wrap via [`IDelegatable<T>`](https://github.com/Arlodotexe/OwlCore.ComponentModel/blob/main/src/IDelegatable.cs). See linked issue for details.
Not provided
=> [improvement] View models implement IDelegatable

src/Shells/StrixMusic.Shells.ZuneDesktop/Controls/Views/Collection/ZuneAlbumCollection.cs, src/Shells/StrixMusic.Shells.ZuneDesktop/Controls/Views/Collection/ZuneTrackCollection.cs
Closes #256 
Apparently this is happening due to race condition when adding collections to custom albumItem/trackitem.
Unsubscribing CollectionChanged fixed it.
Not provided
=> [fix] Fix/crash on album track collection when playing an item on Zune

src/Shared/AppModels/AppRoot.cs
Closes #254
This PR simply adds a field to `StrixMusic.AppModels.AppRoot` containing an instance of `SystemMediaTransportControlsHandler`, initialized with the current `PlaybackHandlerService`. This fixes background playback and enables support for the System Media Transport Controls.
Not provided
=> [fix] Set up SystemMediaTransportControlsHandler in AppRoot

src/Shells/StrixMusic.Shells.Groove/GrooveMusic.xaml, src/Shells/StrixMusic.Shells.Groove/GrooveMusic.xaml.cs
Closes #251 
- The foreground color of the splitview toggle buttons on checked state was incorrect, used lightweight styling to fix it.
- This also includes a fix where checking on toggle button doesn't uncheck others in splitview. 
Not provided
=> [fix] Fixed groove foreground color as well as check state for splitview. 

src/Shared/AppModels/AppRoot.cs
Turned out the linq that was used to prune the Uninitialized cores was incorrect, it was pruning initialized ones on app reload. This has been fixed the cores are loading now on app reload.
Closes #289 
No
Not provided
=> Fixed an issue where core wasn't initialized correctly on app reload.
